### ISSUE TITLE
mqtt issue

### ISSUE THREAD

**Issue by top58525785** [frangoteam/FUXA#414] opened 2022-06-23 07:01 UTC
we have stop publish data to mqtt server long time
but fuxa is not stopping refreshing data
please check the picture and vedio
![微信图片_20220623145755](https://user-images.githubusercontent.com/54358179/175235812-bc564098-c404-4e29-a383-5202b0b06a01.png)

https://user-images.githubusercontent.com/54358179/175235905-745759b9-4fcd-4a60-85e3-e37ca066c500.mp4

https://user-images.githubusercontent.com/54358179/175235925-7a8f46e7-b84c-43cf-a91f-14444f984993.mp4

**Comment by unocelli** [comment] 2022-06-25 15:14
Hi,
is it possible that the problem is that FUXA ask the data to the broker who responds with the value of the last publish?

**Comment by top58525785** [comment] 2022-06-25 15:31
maybe，it is the problem for fuxa mqtt loop data acquire time seettings？
so how to fix it？



发自我的iPhone


------------------ Original ------------------
From: Umberto Nocelli ***@***.***&gt;
Date: Sat,Jun 25,2022 11:14 PM
To: frangoteam/FUXA ***@***.***&gt;
Cc: top58525785 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [frangoteam/FUXA] mqtt issue (Issue #414)





 
Hi,
 is it possible that the problem is that FUXA ask the data to the broker who responds with the value of the last publish?

**Comment by unocelli** [comment] 2022-06-25 16:30
maybe I am misinterpreting the mqtt protocol, but if a sensor only publishes data if it has changes or every minute and for example fuxa process the display or script with logic in a 1-second interval, what value should it take?

**Comment by top58525785** [comment] 2022-06-26 01:42
Actually fuxa should update and dispaly each data from the mqtt broker subscriber，not only the last data？ it should be the real time data from the broker..you can have a test for mqtt if sensor data publish data faster..



发自我的iPhone


------------------ Original ------------------
From: Umberto Nocelli ***@***.***&gt;
Date: Sun,Jun 26,2022 0:30 AM
To: frangoteam/FUXA ***@***.***&gt;
Cc: top58525785 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [frangoteam/FUXA] mqtt issue (Issue #414)





 
maybe I am misinterpreting the mqtt protocol, but if a sensor only publishes data if it has changes or every minute and for example fuxa process the display or script with logic in a 1-second interval, what value should it take?

**Comment by superkalt** [comment] 2022-06-26 10:56
this is a general question. Does fuxa also receive data when no user is logged on?
I see fuxa as pure visualization. it is therefore only necessary to receive and process data when a user is logged on.
MQTT has the "retain" function. If "Retain=true" the broker saves the last data transfer and when a new "client" logs in and subscribes to a "topic" he gets this last value. if "retain=false" it will not get any data until new data is sent again.

**Comment by unocelli** [comment] 2022-06-26 12:02
@superkalt I like your proposal, adding a configurable timeout, default 60 seconds:
- timeout < orange < 5 * timeout
- 5 * timeout < grey < 10 * timeout

**Comment by top58525785** [comment] 2022-06-27 05:26
So Unocelli:
How to fix the problem as vedio shows
IT display realdata and then zero data?

**Comment by superkalt** [comment] 2022-06-27 17:16
> So Unocelli: How to fix the problem as vedio shows IT display realdata and then zero data?

hmmm, come down.

**Comment by superkalt** [comment] 2022-06-27 17:19
> @superkalt I like your proposal, adding a configurable timeout, default 60 seconds:
> 
> * timeout < orange < 5 * timeout
> * 5 * timeout < grey < 10 * timeout

perhaps a good time to separate the processing of the values from the visualization?

**Comment by serite** [comment] 2022-07-03 11:49
this problem is same as  #404

**Comment by top58525785** [comment] 2022-07-04 02:42
@serite  is the problem fixed?

**Comment by jcxjcx123** [comment] 2022-07-04 02:48
I had this problem before, but I pulled the latest version and the problem was gone

**Comment by unocelli** [comment] 2022-07-07 19:24
I am looking but I cannot reproduce it

**Comment by ZhuNathan** [comment] 2022-10-07 12:15
I test this issue with v1.1.8, it will be normal after I creat the new mqtt tags, but the issue will happen after I click "Save Project", it just an appearance what I see, I didn't find the root, I hope it will be helpful for this issue fixing.
https://user-images.githubusercontent.com/49235335/194548008-0b5ea247-c768-4886-8aac-f32897bb142d.mp4

**Comment by unocelli** [comment] 2022-10-08 07:20
Hi, 
Thanks for the report, so I could reproduce it and I think I fixed it, can you confirm me?

**Comment by ZhuNathan** [comment] 2022-10-08 16:34
> Hi, Thanks for the report, so I could reproduce it and I think I fixed it, can you confirm me?

I test this in docker, it worked normally, that's wonderful!

**Comment by unocelli** [comment] 2022-10-12 18:12
I am going to close this as resolved. let me know if you have any issues.

**Closed by unocelli** 2022-10-12 18:12 UTC
Labels: bug, fixed
