### ISSUE TITLE
[BUG] attachment corrupted when sending report by email

### ISSUE THREAD

**Issue by zblack88** [frangoteam/FUXA#1457] opened 2024-10-25 20:27 UTC
**Describe the bug**
When you set up and execute a report, if you download it from the editor interface it works, but if you try to open the report from the received email the attachment is corrupted.
I saw the dimension of the attachment is lower (2.5kB) then the original report dimension (15kB).

**To Reproduce**
1. Set up a  Report filling the "email recipient address" field.
2. Set up properly the SMTP service
3. Execute the report
4. See the received email

**Expected behavior**
Email attachment equal to the report downloaded from the editor interface

**Environment**
 - FUXA version: 1.2.0-1943
 - Platform/OS: windows 10
 - Browser: chrome and edge

**Comment by jingshui127** [comment] 2024-11-21 03:35
不能正确显示中文字符。
比如变量是中文的，PDF将显示为乱码！

**Comment by jingshui127** [comment] 2024-11-26 01:39
![image](https://github.com/user-attachments/assets/a0c06457-35a2-426a-a787-4135c17b0858)

**Comment by unocelli** [comment] 2024-11-29 07:59
Hi, is it possible that it is an OS problem? installed in docker container? Try investigating

**Comment by unocelli** [comment] 2024-12-11 18:54
I assume the issue has been resolved in the meanwhile. I'm therefore going to close this issue.

**Closed by unocelli** 2024-12-11 18:54 UTC
Labels: need more info, unconfirmed

**Comment by zblack88** [comment] 2024-12-11 19:04
To be honest, it have not been resolved.
Checked everything, but attachment continue coming corrupted.
If you want I can forward the email received.

Il Mer 11 Dic 2024, 19:55 Umberto Nocelli ***@***.***> ha
scritto:

**Comment by unocelli** [comment] 2025-02-14 19:31
The problem is not to have e corrupted attachment, is how we can reproduce the issue
