### ISSUE TITLE
svg import issue

### ISSUE THREAD

**Issue by patson12** [frangoteam/FUXA#866] opened 2023-07-14 12:19 UTC
i am uploding some svgs, but it didnt reflect properly in editor .. attacyhing some svg .. can you plz check it?

![Bank](https://github.com/frangoteam/FUXA/assets/96180028/36120993-7591-4296-baa1-85b385349ef9)
![calculator](https://github.com/frangoteam/FUXA/assets/96180028/2ae681cc-2bd4-478c-adbe-8059f448944f)
Hii,

![Amusement Park](https://github.com/frangoteam/FUXA/assets/96180028/7ad8f0c1-231f-4064-8a32-c5dc6235443e)

**Comment by unocelli** [comment] 2023-10-13 14:14
In the last version there is a new add image link that solve the problem.
![image](https://github.com/frangoteam/FUXA/assets/48684550/022690a6-1667-4286-916b-c27be154b502)

**Comment by guiview** [comment] 2023-10-27 04:13
![Airport](https://github.com/frangoteam/FUXA/assets/149062747/5d2c797a-5cce-466b-9f00-df30a54408c9)

This image import working show but not perfect import this image

**Comment by unocelli** [comment] 2023-10-31 20:44
I can't reproduce your issue
![image](https://github.com/frangoteam/FUXA/assets/48684550/e2364eab-b679-4928-8333-f1c7e959b808)

**Comment by unocelli** [comment] 2023-12-31 19:33
I’m going to close this as resolved. let me know if you have any issues.

**Closed by unocelli** 2023-12-31 19:33 UTC
Labels: need investigation, solved
