### ISSUE TITLE
User not warned about session expiration

### ISSUE THREAD

**Issue by IonuDragomir1** [frangoteam/FUXA#626] opened 2022-12-06 14:39 UTC
Hello,

I encountered a bug about FUXA session. The scenario is the following:
1) I login FUXA with an admin created user which expires in one day ('1d' set in server settings which are located in 'server\_appdata\settings.js' file)
2) After one day elapsed, **the user is not warned that the session expired**. In this moment, if the user continues to work on project and at some point wants to save the project, the error message "_Project save failed_" appears in the lower right corner. Most of the users, me included, are tempted to refresh the browser. This action leads to losing all the modifications made since the session expired until the refresh button was pressed. So, before the session expires, the user has to be warned the session is about to expire in order to have time to save the modifications. Another option, the most useful one, would be that right after the session expires, the login window to be displayed and the user to be able to continue working after a successful login. If the second option is not possible, the user should be cyclically  warned (like it's warned when the connection to a device is not established) that the session has expired and has to login again.
3) It'd be very useful if the user could choose if the session expires or not. There are many cases where is no need the session to expire. A suggestion would be add a check box on creation/editing user window. (please see below image)

![image](https://user-images.githubusercontent.com/58516894/205935200-c108b5a2-8f16-46dd-b6b5-71900a7c037a.png)

If the user chooses to use a sessions which expires, should be able to choose from interface session's duration.

**Comment by unocelli** [comment] 2022-12-14 18:40
Hi,
Thanks for your report, needs to be improved, perhaps with a polling.

**Comment by fanhai** [comment] 2023-02-20 06:10
Do I have to do the login interface myself？

**Comment by unocelli** [comment] 2023-02-25 22:09
@fanhai we would appreciate your help :wink:

**Comment by unocelli** [comment] 2023-12-31 18:45
In the new versions at a logout the view jumps to the configured Start View, so I guess the issue is no longer current.
I will therefore close this issue, feel free to re-open it if something is still not working.

**Closed by unocelli** 2023-12-31 18:45 UTC
Labels: improvement
