### ISSUE TITLE
error comes up when  run test for Script

### ISSUE THREAD

**Issue by top58525785** [frangoteam/FUXA#386] opened 2022-06-05 05:59 UTC
HI fuxa team:
i meet a error when using run test for script

 >Http failure response for /api/runscript: 400 Bad Request

How to fix?
Thanks

**Comment by unocelli** [comment] 2022-06-06 14:55
Hi,
if you share your script maybe I can help you, in any case you can use console.log to debug

**Comment by top58525785** [comment] 2022-06-07 04:38
HI FUXA TEAM:
i write as what you example show , also it doesn't work
I use Internal Device Tag to do
Please check the attachment Picture
![111](https://user-images.githubusercontent.com/54358179/172297119-2f755e4e-7db0-4031-9c34-b12d1e6d38c9.png)

**Comment by unocelli** [comment] 2022-06-07 17:08
internal device is only for frontend function, the flow don't go to backend, I have to remove it from the choose, please use FUXA Server tags

**Comment by top58525785** [comment] 2022-06-07 23:59
Thanks for reply
But my question is that if we use internal device tag，we need to some simulation data with script， it
will not support？
Jason



发自我的iPhone


------------------ Original ------------------
From: Umberto Nocelli ***@***.***&gt;
Date: Wed,Jun 8,2022 1:08 AM
To: frangoteam/FUXA ***@***.***&gt;
Cc: top58525785 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [frangoteam/FUXA] error comes up when  run test for Script (Issue#386)





 
internal device is only for frontend function, the flow don't go to backend, I have to remove it from the choose, please use FUXA Server tags

**Comment by unocelli** [comment] 2022-06-08 19:48
No, isn't supported, you can use FUXA Server tag to make simulation
![image](https://user-images.githubusercontent.com/48684550/172704351-5ee0fe5e-c57f-4d97-8e0b-7dfd8aaf6254.png)

**Comment by top58525785** [comment] 2022-06-09 02:43
HI unocelli
Thanks for you reply asap
I did what as you said, the scipt run is no response
please check the attachment
![1](https://user-images.githubusercontent.com/54358179/172752965-642f3ae9-1c66-400a-9479-c7663b90f9c9.png)
![2](https://user-images.githubusercontent.com/54358179/172752976-792f725f-01fb-4e9f-ba9e-9894fe910b50.png)

**Comment by top58525785** [comment] 2022-06-09 10:18
does fuxa tag support script？



发自我的iPhone


------------------ Original ------------------
From: Umberto Nocelli ***@***.***&gt;
Date: Thu,Jun 9,2022 3:48 AM
To: frangoteam/FUXA ***@***.***&gt;
Cc: top58525785 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [frangoteam/FUXA] error comes up when  run test for Script (Issue#386)





 
No, isn't supported, you can use FUXA Server tag to make simulation

**Comment by unocelli** [comment] 2022-06-09 22:05
if you do not receive the console message, then the problem is not the script
![image](https://user-images.githubusercontent.com/48684550/172953137-832d90ba-99c2-4331-a0c1-80b073687f42.png)

**Comment by SNoble6** [comment] 2022-06-17 16:17
Is there a way to do:
`import {Buffer} from 'node:buffer';`
?

**Comment by unocelli** [comment] 2022-07-24 20:28
going to close this as resolved. let me know if you have any issues.

**Closed by unocelli** 2022-07-24 20:28 UTC
