### ISSUE TITLE
mqtt broker topic to subscribe problem

### ISSUE THREAD

**Issue by guang067** [frangoteam/FUXA#435] opened 2022-08-01 07:47 UTC
Dear teams:

     i am try the 1.1.7 version,   node version is 12.6.3,  and npm version is 6.14.4。 

     Devices setting seems fine:
![image](https://user-images.githubusercontent.com/6702824/182098766-12671885-72c1-42e9-895d-2cfbd2fed065.png)

but when add device tags and try to browser Topics on broker, no result found.   are there any thing wrong?    
![image](https://user-images.githubusercontent.com/6702824/182098156-b3935e54-1ec7-42e0-ab31-933be8fe7efe.png)

public works ok,  and i use rabbitmq btw, thanks!
![image](https://user-images.githubusercontent.com/6702824/182099359-3dbcd8d8-24c2-4f83-978d-aaf8a404434b.png)

![image](https://user-images.githubusercontent.com/6702824/182099223-d2ab1539-45b9-4aeb-8d01-90eaff7d1446.png)

**Comment by acgiesbrecht** [comment] 2022-08-05 17:33
you need to add a # at the end of your topic stirng to browse al child topics: eg: iot/gw/device/#

**Comment by guang067** [comment] 2022-08-25 07:13
> you need to add a # at the end of your topic stirng to browse al child topics: eg: iot/gw/device/#

have try but still not work, also just use # to search all topic,  is sth wrong in rabbitmq? 
![image](https://user-images.githubusercontent.com/6702824/186598560-9ffb7282-fee4-4ee1-8334-9c9e01b5362b.png)


![image](https://user-images.githubusercontent.com/6702824/186598088-6164e45a-5bca-4e71-a39a-62d866a8f3b1.png)


![image](https://user-images.githubusercontent.com/6702824/186598371-97018b89-7cdc-4712-b195-67f87dbf2ec7.png)

![image](https://user-images.githubusercontent.com/6702824/186599045-b51fd91e-cd6d-4d88-a039-01ffc76c1eb2.png)

![image](https://user-images.githubusercontent.com/6702824/186599141-d6e0f468-acf7-4edc-af35-388a9b4bb2f2.png)

![image](https://user-images.githubusercontent.com/6702824/186599362-661faf92-38f7-4922-b4bb-9041c88674b4.png)


and the logs shows:
![image](https://user-images.githubusercontent.com/6702824/186598446-d7f8a840-9239-4f29-83d8-97bbb5349b4b.png)

**Comment by unocelli** [comment] 2022-09-15 19:17
Hi,
I suppose the problem is not solved.
what happens if you try to discover an existing topic address?

**Comment by guang067** [comment] 2022-09-22 07:41
> 
thanks for reply,    and attached is the screenshot of this problem.  

https://user-images.githubusercontent.com/6702824/191687321-c87cecc4-8bbf-4563-ba75-f01983316e4e.mp4

**Comment by unocelli** [comment] 2022-09-26 18:58
something is missing

**Comment by unocelli** [comment] 2022-09-29 19:38
sorry my mistake...
have you already tried to test mqtt of FUXA by connecting to another broken like mosquitto?

**Comment by jyb1975** [comment] 2022-12-01 16:13
I'm facing the same problem...

**Comment by jyb1975** [comment] 2022-12-12 04:47
> I'm facing the same problem...
i got the reason. FUXA is using topic "#" to browse all topic on broken. However, FUXA receive nothing to some topics while those topics don't retain last value. It seems fine for MQTT5.0 broken in case of setting RETAIN flag of topic (last value will be retained on broken). RabittMQ supports MQTT3.1.1 only which RETAIN flag seems not working. 

one option solution, producer can send value to topic in little interval, say 1 second. FUXA should be working. 

anyway, is it possible to add topics on broken to input topic as well?

**Comment by jyb1975** [comment] 2022-12-12 04:48
> I'm facing the same problem...

i got the reason. FUXA is using topic "#" to browse all topic on broken. However, FUXA receive nothing to some topics while those topics don't retain last value. It seems fine for MQTT5.0 broken in case of setting RETAIN flag of topic (last value will be retained on broken). RabittMQ supports MQTT3.1.1 only which RETAIN flag seems not working. 

one option solution, producer can send value to topic in little interval, say 1 second. FUXA should be working. 

anyway, is it possible to add topics on broken to input topic as well?

**Comment by unocelli** [comment] 2023-03-19 17:33
I am going to close this as resolved, let us know if you have any issues.

**Closed by unocelli** 2023-03-19 17:33 UTC
Labels: solved
