### ISSUE TITLE
[BUG] TypeError: Cannot read properties of undefined (reading 'layout')

### ISSUE THREAD

**Issue by IonuDragomir1** [frangoteam/FUXA#1082] opened 2024-02-15 11:17 UTC
Hi,
I get on browser's console the error:  

> TypeError: Cannot read properties of undefined (reading 'layout')

This error is encountered  when I add an input field on a screen which is called on panel control. 

**Screenshots**
![image](https://github.com/frangoteam/FUXA/assets/58516894/26c0de05-9733-4749-8daf-45ee361d96c9)

**Environment**
 - FUXA version: 1.1.18 - 1421
 - Node.js version: v14.21.3
 - npm version: 6.14.18
 - Platform/OS: WIN 10
 - Browser: Chrome

**Comment by unocelli** [comment] 2024-02-15 17:15
Hi, thanks for the report.
can you please attach the project so that we can reproduce it?

**Comment by IonuDragomir1** [comment] 2024-02-16 07:28
[fuxa-project_InputField.json](https://github.com/frangoteam/FUXA/files/14307740/fuxa-project_InputField.json)
To get the error, press on E1 button to open view E1 in panel. 
I didn't test for all fuxa's controls. The error might appear also on others.

**Comment by unocelli** [comment] 2024-02-16 19:57
Hi, thanks for the project...I can't reproduce the exception. please try with the last one version

**Comment by IonuDragomir1** [comment] 2024-02-19 08:29
Hi, I have used the last version of FUXA (Version 1.1.18-1421). It's not this the last?

**Comment by unocelli** [comment] 2024-02-23 20:57
1.1.18-1431

**Comment by IonuDragomir1** [comment] 2024-02-26 07:35
Yes. With this version, I don't get the error.

**Comment by unocelli** [comment] 2024-03-17 18:53
I’m going to close this as resolved. let me know if you have any issues.

**Closed by unocelli** 2024-03-17 18:53 UTC
Labels: solved
