### ISSUE TITLE
Proposal. Add views templates for cards/dialogs

### ISSUE THREAD

**Issue by NikolayMurha** [frangoteam/FUXA#92] opened 2021-01-26 17:17 UTC
Hello.

I have dashboard with >40 semaphores and I need dialog for each of them.
All dialogs identical, but variables different for each dialog. 
Now I create 40 different views for each dialog.
I think, will be good to make views templates with placeholders instead of variables names, and set variables names on dialog properties.

**Comment by unocelli** [comment] 2021-05-07 07:50
I think the issue is solved. I'm therefore going to close it.

**Closed by unocelli** 2021-05-07 07:50 UTC
Labels: enhancement
