### ISSUE TITLE
modbus tcp, register not supported by device - query bug?

### ISSUE THREAD

**Issue by cicci44** [frangoteam/FUXA#71] opened 2020-08-22 06:24 UTC
device CPU look like this, readings are fine:
![bild](https://user-images.githubusercontent.com/1296978/90949971-c6f85680-e44d-11ea-9db7-9d250f761a78.png)
but if i add 300025, int16.. 
i get no reading but this:
![bild](https://user-images.githubusercontent.com/1296978/90950002-fa3ae580-e44d-11ea-90a9-8e6acd583165.png)
however.. if i disable device CPU, and make a copy called TEST i get values like this:
![bild](https://user-images.githubusercontent.com/1296978/90949954-afb96900-e44d-11ea-9c84-cf9fe8e490e3.png)

im not sure if im doing wrong or if theres a hardware related issue...
![bild](https://user-images.githubusercontent.com/1296978/90950091-ca401200-e44e-11ea-890a-91a790815ac4.png)
second picture
![bild](https://user-images.githubusercontent.com/1296978/90950291-6dddf200-e450-11ea-8d2b-f34efaffc3cc.png)

how can i make a second query to get the next serie of data if the query is too long?

**Comment by unocelli** [comment] 2020-08-23 18:35
Hi,
I tested with ModRSSim2 (modbus slave simulator) and I can't reproduce the
problem, I think that is a problem with the hardware (slave) that you are
using.
[image: Capture.PNG]

[image: Unbenannt.PNG]

**Comment by cicci44** [comment] 2020-08-23 19:55
ok. thanks for the hint, im not familiar with modbus tcp but will build simple test script soon to see if the hardware can handle two queries after each other from diffrent place in the register. The same hardware but older revision used modbus RTU and the test code seems to loop out queries after each other and when all is done, it publish the result, might just be so simple with this..
 
Maybe a feature to implantate if its true 👍

**Comment by cicci44** [comment] 2020-08-29 12:52
this code below works. It seems that hardware-side does not like to read all data in one sweep. After consulted around it seems to be common issue of some hardware manufacturers.. as i understand, i cant read over a "black hole" in the register.
![bild](https://user-images.githubusercontent.com/1296978/91637127-609fa500-ea06-11ea-9a8a-240c4fef5bb5.png)

Is it possible to add a feature to add multiple queries in next update? that would be great to try. 👍 

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-


```from pyModbusTCP.client import ModbusClient
import time
SERVER_HOST = "192.168.1.10"
SERVER_PORT = 502
c = ModbusClient()
# modbus server IP och port
c.host(SERVER_HOST)
c.port(SERVER_PORT)

while True:
    # etablera eller återetablera förbindelse..
        #connect or reconnect...
    if not c.is_open():
        if not c.open():
            print("unable to connect to "+SERVER_HOST+":"+str(SERVER_PORT))
        print ("connect or reconnecting..")
        #if function is available....
    # om funktion tillgänglig, läs register..
    if c.is_open():
        # start at address 0 and read to 13, store in query1
        # Börja på address 0 och läs 13st.. lagra det i query1
        query1 = c.read_input_registers(0, 13)
        time.sleep(2)
        # läs ytterlig och lagra det i query2
        # read som more and store it in query2
        query2 = c.read_input_registers(22, 10)
        # if success display registers
        if query2:
                print ("query1")
                print ("reg ad #0 to 13: "+str(query1))
                print ("query2")
                print ("reg ad #22 to 32: "+str(query2))

    # sleep 2s before next polling
        #vänta..
    time.sleep(2)

**Comment by unocelli** [comment] 2020-08-30 19:39
Hi,
I understand...can you try my last committed code and tell me if will work?
Thanks

**Comment by cicci44** [comment] 2020-09-02 18:54
> 
> 
> Hi,
> I understand...can you try my last committed code and tell me if will work?
> Thanks

testing the last committed code, it seems to work 👍 

however, seems to be another issue after 1-2min, but will make a new issue of that (not sure yet if the error is a issue)
![bild](https://user-images.githubusercontent.com/1296978/92024394-72fb4500-ed5e-11ea-8b4e-c0cacf6e64fc.png)

**Comment by unocelli** [comment] 2020-09-02 20:19
how many modbus Tags have you configured?
If you change the polling interval DEVICE_POLLING_INTERVAL in 'server/runtime/devices/device.js' (for example to 5 seconds) what happens?

**Comment by cicci44** [comment] 2020-09-03 18:18
> 
> 
> how many modbus Tags have you configured?
> If you change the polling interval DEVICE_POLLING_INTERVAL in 'server/runtime/devices/device.js' (for example to 5 seconds) what happens?

i got for the moment eight modbus tags but the error still there, tried raise to 10sec. 
![bild](https://user-images.githubusercontent.com/1296978/92152058-64766180-ee22-11ea-9b4b-a1b0ef3b1578.png)

**Comment by unocelli** [comment] 2020-09-03 20:34
Hi,
I send you a 'modbus/index.js' file where I improved the error description and increment to 10 seconds the client timeout

[index.zip](https://github.com/frangoteam/FUXA/files/5171022/index.zip)

**Comment by cicci44** [comment] 2020-09-05 16:01
> 
> 
> Hi,
> I send you a 'modbus/index.js' file where I improved the error description and increment to 10 seconds the client request timeout `client.setTimeout(10000);`
> 
> [index.zip](https://github.com/frangoteam/FUXA/files/5171022/index.zip)

"Timed out", tried raise deviceCloseTimeout in rundime/devices.devices.js to 5sec, didnt work.
![bild](https://user-images.githubusercontent.com/1296978/92308955-9feb6a00-efa1-11ea-95c4-096f2d5d2c73.png)

**Comment by unocelli** [comment] 2020-09-05 17:13
I suspect the problem is that the Promise.all function is too fast for the Device. what happens if you configure only one tag, (so that only one query is made per poll interval?

**Comment by cicci44** [comment] 2020-09-06 07:58
> 
> 
> I suspect the problem is that the Promise.all function is too fast for the Device. what happens if you configure only one tag, (so that only one query is made per poll interval?

this was the settings
![bild](https://user-images.githubusercontent.com/1296978/92321007-76285680-f026-11ea-8640-d3e21a262895.png)
this was the result
![bild](https://user-images.githubusercontent.com/1296978/92320998-5abd4b80-f026-11ea-8237-bf1b36528b6a.png)
however i just remember i made a change in FUXA/server/main.js back for a while when i had issues with connection to the GUI, that cannot make the issue?.
![bild](https://user-images.githubusercontent.com/1296978/92321045-f484f880-f026-11ea-81f0-0edf0f57a9be.png)

**Comment by unocelli** [comment] 2020-09-06 09:21
I send you a test to see how the used 'modbus-serial' library and your hardware works with a simple query.
[modbus-serial_test.zip](https://github.com/frangoteam/FUXA/files/5179330/modbus-serial_test.zip)

>npm install
>npm start

**Comment by cicci44** [comment] 2020-09-06 11:41
> 
> 
> I send you a test to see how the used 'modbus-serial' library and your hardware works with a simple query.
> [modbus-serial_test.zip](https://github.com/frangoteam/FUXA/files/5179330/modbus-serial_test.zip)
> 
> > npm install
> > npm start

seems ok for the moment but i needed to change 192.168.1.155 (raspberry address) to 192.168.1.153 (ftx), will let it run for a while and see if something happens
![bild](https://user-images.githubusercontent.com/1296978/92324889-3c674800-f046-11ea-8218-9b3891d31700.png)

**Comment by unocelli** [comment] 2020-09-06 13:50
Hi,
maybe the problem is in the wait for the response of the device before continuing.
I send you a new 'modbus/index.js' file where I changed the polling function:

this.polling = **async** function () {
  readVarsfnc.push(**await** _readMemory(...

[index.zip](https://github.com/frangoteam/FUXA/files/5179728/index.zip)

**Comment by cicci44** [comment] 2020-09-06 19:10
> 
> 
> Hi,
> maybe the problem is in the wait for the response of the device before continuing.
> I send you a new 'modbus/index.js' file where I changed the polling function:
> 
> this.polling = **async** function () {
> readVarsfnc.push(**await** _readMemory(...
> 
> [index.zip](https://github.com/frangoteam/FUXA/files/5179728/index.zip)

this is the result now
![bild](https://user-images.githubusercontent.com/1296978/92333364-26c54300-f085-11ea-8c89-ca87cb7acc60.png)

**Comment by unocelli** [comment] 2020-09-06 21:57
Can you tell me which hardware (device) are you trying to communicate?

**Comment by cicci44** [comment] 2020-09-08 17:49
> 
> Can you tell me which hardware (device) are you trying to communicate and witch nodejs version have you installed in Raspberry?

im trying communicate with Heru 100 T EC with node v12.16.2, just saw theres a firmware update on the ftx, going to test upgrade firmware to see if Coms get more stable..
https://fsp.ostberg.com/products/4397/heru-100-t-ec/?region=en&lang=en

**Closed as completed** 2021-10-12 19:09 UTC
