### ISSUE TITLE
Why page home still show when not login yet? 

### ISSUE THREAD

**Issue by saufister** [frangoteam/FUXA#529] opened 2022-10-08 10:19 UTC
Hi,  Is there a way to hide home page before user successfully log in ?

**Comment by unocelli** [comment] 2022-10-10 21:20
there isn't a welcome page but you can set the navigation permissions

**Comment by mauroalexandre** [comment] 2022-10-11 10:42
Maybe hide the view from background from login modal is a good feature.

@unocelli let me know your opnion and I'll try open PR.

**Comment by unocelli** [comment] 2022-10-30 09:29
@mauroalexandre Hi and sorry for the delay. Yes I think is a good idea. I will wait your PR :D

**Comment by unocelli** [comment] 2023-12-31 19:08
In the new versions at a logout the view jumps to the configured Start View, so I guess the issue is no longer current.
I will therefore close this issue, feel free to re-open it if something is still not working.

**Closed by unocelli** 2023-12-31 19:08 UTC
Labels: feature
