### ISSUE TITLE
Popup chart legend doesn't represent float values.

### ISSUE THREAD

**Issue by microdeth** [frangoteam/FUXA#739] opened 2023-03-16 20:30 UTC
Hi, the same thing again -- I see it was fixed for the real-time graphs but not for the historical, see the message below.

Thanks,
Dima.

              Hi, need to reopen the issue. Issue was fixed for 'Realtime' chart show mode, but for 'History' the problem persists (see the screenshot). Thanks in advance for your assistance.
<img width="546" alt="image" src="https://user-images.githubusercontent.com/127868343/225688149-d4545de4-081d-4ae3-9865-72ab8cadace8.png">

_Originally posted by @microdeth in https://github.com/frangoteam/FUXA/issues/732#issuecomment-1472307829_

**Comment by unocelli** [comment] 2023-03-18 19:30
Hi, it is a duplicate of #732

**Closed by unocelli** 2023-03-18 19:30 UTC
Labels: duplicate
