### ISSUE TITLE
History charts can't draw curves

### ISSUE THREAD

**Issue by artofegg** [frangoteam/FUXA#516] opened 2022-09-29 12:44 UTC
![动画](https://user-images.githubusercontent.com/97082898/193033962-42c68d03-7bd2-4769-ad24-c9c8ad1c5297.gif)
First of all thanks to the author for his great work ! 
I have a problem now . Just finished setting it up  the charts worked fine, after about a few hours, it looked the way it does now,But the data shows it's still working.

**Comment by unocelli** [comment] 2022-09-29 19:16
Hi, Thanks for the report. It looks like a refresh problem of the control.
Can you make some test, so that I can reproduce it? Browser used? Click to refresh chart? Browser refresh F5? has that ever worked?

**Comment by artofegg** [comment] 2022-09-29 23:41
Browser is firefox  105.0.1 64bit for Win 10 , i also tested at the last Chrome for all recommended actions. 
Ten hours later , looks part of it is working up , and first charts can display by local zoom operation use mouse

![动画](https://user-images.githubusercontent.com/97082898/193160505-327358aa-16e3-454e-878e-002b2e4313e2.gif)

**Comment by saufister** [comment] 2022-10-02 02:40
Its also happen to my chart, actually i am from vue js doesnt understand to fix angular js project☺🙏

**Comment by unocelli** [comment] 2022-10-25 16:20
Hi,
I think I have been able to reproduce it and I think the problem is that the FUXA server has recorded 'undefined' values. I will try to fix the issue so that only valid values are recorded.

**Comment by artofegg** [comment] 2022-10-26 00:56
I guess the problem is the mqtt server disconnect randomly , NaN data received by database and web drawing failed. Which area do not have NaN data so it can be selected with the mouse and succeed.

**Comment by artofegg** [comment] 2022-10-27 00:25
> Hi, I think I have been able to reproduce it and I think the problem is that the FUXA server has recorded 'undefined' values. I will try to fix the issue so that only valid values are recorded.


Great minds think alike, thanks your job !

**Comment by unocelli** [comment] 2022-11-13 12:33
I am going to close this as resolved. let me know if you have any issues.

**Closed by unocelli** 2022-11-13 12:33 UTC
Labels: fixed
