### ISSUE TITLE
Object copy and paste does not copy object animations - events

### ISSUE THREAD

**Issue by mariorl** [frangoteam/FUXA#576] opened 2022-11-04 15:38 UTC
Hey there, I get shocked when noticed, some time after testing Fuxa, so that when I animate an object, in "Shape settings/property pane" and set seral fill/stroke color for an item, the animation works gret, but when I try to copy an paste the whole configured item in designer view, lets say, a copy a motor or valve, the animations are not copied to the new object. May be should temporaly solve it by editing the project db with an external sqlite db browser.

**Comment by unocelli** [comment] 2022-11-04 19:04
Hi, please let us know the version that are you using and the shape. I cannot reproduce it.

**Comment by mariorl** [comment] 2022-11-04 19:19
Fuxa 1.1.9 master. I went ahead testing, and noted the issue not happends with all objects with animation capacity. For example a simple square shape linked to a PLC var copy and paste OK along with all animations. The ones who not worked are text and resource/svg. These ones copy and paste without "animation" properties for me. Also noted, if I export a view and then import back, the animations are saved and retrieved ok in the new view. If I edit in external json editor the missing nodes for example for a motor svg animation (  missed "ranges"[] and "variableid":   ) it get fixed when imported to fuxa editor.

**Comment by unocelli** [comment] 2022-11-04 19:59
Ok, we have to fix it, thanks.
about the svg with animation: currently fuxa editor is inflexible and remove the elements that not support. can you send me the svg file?

**Comment by mariorl** [comment] 2022-11-05 08:05
I noticed in the corresponding fuxa project sqlite table to that the view/svg belongs, who the missed arguments on copied element are "ranges"[] and "variableid": filled with the same values of the original view/svg element. Filling them with external text tool fixes it.
Also, I just tested again, for me a text inserted with "text tool", when edited color of text depending on a PLC variable, if then you copy an paste that text in the view designer in order to obtain several texts with same properties, is copied without animations.
![SVG_PUMP_1_OFF](https://user-images.githubusercontent.com/6344456/200110200-09d169e9-6a6f-4dd2-82e8-f7097be46e5c.SVG)

**Comment by mariorl** [comment] 2022-11-14 19:58
Hi, I noticed that, rather than raw copy an paste objects in the editor, the button "duplicate" works OK for copy simple object and its animations, like texts, rectangles etc. So the issue sould be focused only to "Resource" objects, like the pump in previous post. Thanks.

**Comment by unocelli** [comment] 2023-02-05 17:43
I am going to close this as resolved. let me know if you have any issues.

**Closed by unocelli** 2023-02-05 17:43 UTC
Labels: solved
