### ISSUE TITLE
Upload image bug

### ISSUE THREAD

**Issue by wooAo** [frangoteam/FUXA#162] opened 2021-06-08 08:52 UTC
Hi, sir
I want to upload a picture as a component
but after uploading 3 pictures,  i find it gets the same one no matter what pictures i choose
is there any bugs?

**Comment by muzixiaosanshi** [comment] 2021-06-08 09:07
Dear unocelli，
I come across the same question,Could you help to check this ?Thanks in advance.

**Comment by unocelli** [comment] 2021-06-08 15:31
Hi,
with which browser did you try? fuxa version? can you send me the output of browser console by load fuxa frontend and after adding an image?

**Comment by wooAo** [comment] 2021-06-09 01:12
Thanks for replying
I have tried chrome and firefox in local and in your live demo, it remains the same problem
I restart the project, it still dosent work
And version is v1.0.11
Here is the console ater adding 

![image](https://user-images.githubusercontent.com/50292852/121276531-6a452a00-c901-11eb-8ea4-02bbc188a03f.png)

**Comment by unocelli** [comment] 2021-06-09 07:15
I tested in the in [demo](https://frangoteam.github.io/) with png and is working.
which type of image you want to upload? SVG?

**Comment by muzixiaosanshi** [comment] 2021-06-09 07:39
I uploaded format png also and  at the beginning it can work , But if you try several times ,the problem will appear. @unocelli

**Comment by wooAo** [comment] 2021-06-11 09:43
Hi, sir
Is there a lowest browser version limit?
It fails to show up the index page, but stays in loading page and never change
Looking forward to your reply, Thanks

Here is the console and browser info
The OS is ubuntu, not windows
![image](https://user-images.githubusercontent.com/50292852/121666296-aa600480-cadb-11eb-9aef-bbfea3794f9e.png)
![image](https://user-images.githubusercontent.com/50292852/121666323-afbd4f00-cadb-11eb-82c4-f0913dcf7f02.png)

**Comment by unocelli** [comment] 2021-06-14 20:23
@wooAo Hi, I don't know what is the lowest browser version limit. are you sure that the problem is not the installation (nodejs and npm version)? it would be better if you opened another issue, 'Upload image bug' is not the right.

**Comment by AlexVishwa** [comment] 2021-09-27 04:51
I resolved this, try building properly and this issue won't reoccur. I reproduced the bug by running angular server and node server separately, instead one must run it as a complete system.

**Comment by unocelli** [comment] 2021-09-27 06:46
Hi,
Please send me a better description of what you mean...

**Comment by AlexVishwa** [comment] 2021-09-27 06:51
Hi Umberto,
When we try to upload an image it gives a bug of same image and new image is not selected. There is a trick that instead of building using npm start we may use nodemon main.js and vice versa which seems to clear the cache and this bug gets resolved, otherwise it is reproducing.

**Comment by unocelli** [comment] 2021-09-27 07:08
Ok, thank you,
I have to try, I thought I solved it in version 1.1.1

**Comment by AlexVishwa** [comment] 2021-09-27 09:57
No its not. It reproduces after a while.

**Comment by unocelli** [comment] 2021-09-27 20:41
Hi Alex,
it should now be fixed

**Comment by AlexVishwa** [comment] 2021-09-29 16:11
Thanks Unocelli but its not fixed. It still comes up.

**Comment by AlexVishwa** [comment] 2021-09-29 16:13
I have to restart my PC everytime. There lies an issue with clearing cache , it seems.

**Comment by unocelli** [comment] 2021-10-03 19:26
I have tried with many images and different types svg, png, jpg...
do you have any idea how to reproduce it?

**Comment by AlexVishwa** [comment] 2021-10-04 05:42
![Screenshot from 2021-10-04 11-10-46](https://user-images.githubusercontent.com/8532397/135799788-e8af6b22-5f61-4105-b68e-1b778e23c945.png)
![Screenshot from 2021-10-04 11-10-36](https://user-images.githubusercontent.com/8532397/135799793-9893437c-cc39-438c-914b-9b68af6853c5.png)
![Screenshot from 2021-10-04 11-10-31](https://user-images.githubusercontent.com/8532397/135799803-a694a568-46f7-47e9-b650-38c0d056dbdf.png)
See the screenshots

**Comment by unocelli** [comment] 2021-11-16 21:46
I solved it. I will therefore close this issue, feel free to re-open it if something is still not working.

**Closed by unocelli** 2021-11-16 21:46 UTC
Labels: bug
