### ISSUE TITLE
Actions for internal tags

### ISSUE THREAD

**Issue by AlexandruAndrei3** [frangoteam/FUXA#314] opened 2022-03-30 12:43 UTC
Hi,

I have tried your tutorial for scripts. It works great for external tags but internal tags don't seem to work. Did it test it for internal tags as well?
It is possible for the functions to be executed cyclically?

**Comment by unocelli** [comment] 2022-03-30 19:41
Hi,
If you mean internal device, it's only frontend, the script run in backend. you can use the server tags.
I planed to implement the cyclically functionality.

**Comment by AlexandruAndrei3** [comment] 2022-03-31 09:12
I tried to assign a value to an internal tag and got no results. Do I understand that operations with internal tags cannot be performed in a script function?
<img width="648" alt="Screen Shot 2022-03-31 at 12 02 06" src="https://user-images.githubusercontent.com/94168341/161020261-ac7ea07e-1941-449d-b3fc-65dc4b8d613d.png">


I consider that the facility to perform operations with internal tags as well as the transfer of values between external tags to internal ones and vice versa is very important.
Do you think that it is possible to perform these operations in the future?

**Comment by unocelli** [comment] 2022-03-31 19:13
the idea would be to have variables for logic only on the frontend, for this internal (I have to change the name). Whereas in the latest version it is possible to define tags on the device server, which are also accessible on the backend.
<img width="163" alt="image" src="https://user-images.githubusercontent.com/48684550/161131723-06e38a7f-2827-4c5e-ba28-26f52e355db0.png">

**Comment by robsori** [comment] 2022-04-03 15:48
Yes, I noticed in the latest version that we can create tags on the server device. I called them in a simple function and tried to gather their values. The problem is, they can't get any results. Am I wrong somewhere?
I think it is important to be able to make the connection between the server tags and the internal tags.

**Comment by unocelli** [comment] 2022-04-03 18:08
have you tried creating a new project to test the server tags? it is possible that projects made with older versions do not enable the server to check tags. I have to investigate.

**Comment by robsori** [comment] 2022-04-03 18:11
Thank you for your answer. Okay, I'll investigate tomorrow and tell you what I got.

**Comment by robsori** [comment] 2022-04-04 11:47
I tested the latest version of Fuxa and I confirm that the mathematical operations performed between two tags declared on the server side and called in a function is possible. Thanks.

**Comment by unocelli** [comment] 2022-04-05 16:01
Great,
so we can forget about giving the internal tags to the server. :wink:

**Comment by Rainproof** [comment] 2022-05-08 20:26
Yes. I also first tried to work with internal variables. Then I read these messages and made tags on the server. Everything is working. All mathematical functions are executed.

**Comment by unocelli** [comment] 2022-07-24 20:28
going to close this as resolved. let me know if you have any issues.

**Closed by unocelli** 2022-07-24 20:28 UTC
