### ISSUE TITLE
Get two parameters for a function from script system function

### ISSUE THREAD

**Issue by IonuDragomir1** [frangoteam/FUXA#1127] opened 2024-03-25 08:06 UTC
Hi,
I have created and added a function on script system function. My function requires two parameters (two tag ids). So when I call the function on script editor, tag selection window is opening. Here I must select the parameters (the two tags), but I'm allowed to select only one. The second parameter I have to type manually or to call the $getTag function. What could I do to get both tags when calling my function?

**Comment by unocelli** [comment] 2024-03-27 21:49
Hi, sorry but I don't understand, can you send me an image that clarifies?

**Comment by IonuDragomir1** [comment] 2024-03-28 07:56
Hi,
My function requires  2 word tags as parameters.  When I click on `$WordsToReal`, tag selection window is opening.
In the below image, I can select only one tag. On tag selection window, I need to select both tags (WORD1 and WORD2).

![image](https://github.com/frangoteam/FUXA/assets/58516894/0ff54428-52da-4f81-ba7c-a530c48586e3)

What should I do to be able to select both tags from tag list?

**Comment by IonuDragomir1** [comment] 2024-03-29 07:58
Thanks for your reply!
I have modified on `script-editor.component.ts` multiSelection: true. Now I'm able to select both tags. 

![image](https://github.com/frangoteam/FUXA/assets/58516894/ca37b75f-a456-464f-ab47-c668c0dd352a)

My question is what should I do to get both of them called inside my function? This what I get after selecting both tags:

![image](https://github.com/frangoteam/FUXA/assets/58516894/a5a43a9c-7697-45f8-bbfb-9aec850f233d)

What I should get is: 
![image](https://github.com/frangoteam/FUXA/assets/58516894/9122345a-46ce-4fc2-b381-6c5a8d823e06)

I have tried to modify on `client\src\app\_models\script.ts` the  `$WordsToReal`'s params in so many manners, but I couldn't get both tags. 

![image](https://github.com/frangoteam/FUXA/assets/58516894/e5cc27f2-c637-43d2-bdae-115dd9971fba)


What should I do?

**Comment by IonuDragomir1** [comment] 2024-03-29 08:15
Thanks for reply!
I have modified on `scipt-editor.component.ts` multiSelection: true. Now I'm able to select both tags. But after selecting them, what I get is:
![image](https://github.com/frangoteam/FUXA/assets/58516894/836537de-28cf-4191-bf8d-943fc059f909)


What should I get is:
![image](https://github.com/frangoteam/FUXA/assets/58516894/c6161d37-b5aa-49d4-b2d4-3e550d89a035)

I have modified on `client\src\app\_models\script.ts` $WordsToReal's params in so many manners but I couldn't succeed.
![image](https://github.com/frangoteam/FUXA/assets/58516894/a2f17d0e-00a2-4d8a-b31b-9dcb47e67570)

What should I do to get both parameters called on $WordsToReal function?

**Comment by unocelli** [comment] 2024-04-13 06:12
The issue is not so simple, because I would also like to be able to define in which order they should be bound

**Comment by unocelli** [comment] 2024-10-27 12:17
I’m closing this issue since there is nothing feasible

**Closed by unocelli** 2024-10-27 12:17 UTC
