### ISSUE TITLE
[BUG] TypeError: Cannot read properties of undefined (reading 'views')

### ISSUE THREAD

**Issue by IonuDragomir1** [frangoteam/FUXA#1083] opened 2024-02-15 12:13 UTC
Hi,
I get on browser's console the error:

> TypeError: Cannot read properties of undefined (reading 'views')

I get this error when trying to open a page, card or dialog from a view which is called on a panel control.
The Open iframe and Open Window actions are working properly when are  fired from a view which is called on a panel control. 

**Screenshots**
![image](https://github.com/frangoteam/FUXA/assets/58516894/31b6f61f-56dc-4341-9e7f-bd151a96aa10)

**Environment**
 - FUXA version: 1.1.18 - 1421
 - Node.js version: v14.21.3
 - npm version: 6.14.18
 - Platform/OS: WIN 10
 - Browser: Chrome

**Comment by unocelli** [comment] 2024-02-15 17:15
Hi, thanks for the report.
can you please attach the project so that we can reproduce it?

**Comment by IonuDragomir1** [comment] 2024-02-16 07:22
[fuxa-project_Open.json](https://github.com/frangoteam/FUXA/files/14307721/fuxa-project_Open.json)

**Comment by unocelli** [comment] 2024-02-16 19:57
Hi, thanks for the project...I can't reproduce the exception. please try with the last one version

**Comment by unocelli** [comment] 2024-02-23 20:56
1.1.18-1431

**Comment by IonuDragomir1** [comment] 2024-02-26 07:37
Even though I don't get the error anymore, the  open  page, card or dialog are not working from a view which is called on a panel control.

**Comment by unocelli** [comment] 2024-03-17 18:52
I’m going to close this as resolved. let me know if you have any issues.

**Closed by unocelli** 2024-03-17 18:52 UTC
Labels: solved
