### ISSUE TITLE
How to improve the issue of management page lag when the system tag exceeds 5000?

### ISSUE THREAD

**Issue by gospeell** [frangoteam/FUXA#872] opened 2023-07-20 05:23 UTC
Hi, I have an idea to use FUXA on projects with more than 5000 system tag . Currently, during simulation testing, there was a serious lag in the management page at 5000 system tag . How can I improve this problem?

Cmd error
`(node:11564) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 finish listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit`

**Comment by unocelli** [comment] 2023-07-25 19:05
Hi, we have activated a option that have to be test. you find it into the master branch.
Let me know if it works.
![image](https://github.com/frangoteam/FUXA/assets/48684550/5a6498e8-19aa-4513-a948-fce9a47e8d39)

**Comment by hxjackcn** [comment] 2023-07-25 23:57
Node.js cannot be multi-threaded. Let me test it, 5000 points, for opcua, set it to refresh in 30 seconds. If the refresh time is too small, it won't be able to handle it.

**Comment by hxjackcn** [comment] 2023-07-25 23:59
This is determined by the mechanism of Node.js itself. My current solution is that I build multiple sites, split the points, each site does not exceed 2000 points. My projects generally have around 30 million points, or even more.

**Comment by hxjackcn** [comment] 2023-07-26 00:05
The running stability is not bad, I have a project, I have used fuxa for more than 2 years, and it is still running stably.

**Comment by gospeell** [comment] 2023-07-26 09:02
> Hi, we have activated a option that have to be test. you find it into the master branch. Let me know if it works. ![image](http://user-images.githubusercontent.com/48684550/256009519-5a6498e8-19aa-4513-a948-fce9a47e8d39.png)

 Okay, arrange testing as soon as possible

**Comment by gospeell** [comment] 2023-07-26 09:03
> This is determined by the mechanism of Node.js itself. My current solution is that I build multiple sites, split the points, each site does not exceed 2000 points. My projects generally have around 30 million points, or even more.

Hello, are multiple fuxa deployed on the same computer?

**Comment by hxjackcn** [comment] 2023-07-31 00:28
It's all right, I usually deploy multiple sites on one computer and deploy multiple computers.

**Comment by gospeell** [comment] 2023-08-02 04:29
Hi, I have tested using the new version and now the report is as follows:

1. 4991 system tag tested

2. There is still a problem with stuck backend settings, mainly manifested in the device page and save menu options being stuck and unresponsive

**Comment by gospeell** [comment] 2023-08-02 04:30
> It's all right, I usually deploy multiple sites on one computer and deploy multiple computers.

Do you have any tutorials in this area？

**Comment by unocelli** [comment] 2023-08-12 21:22
Hi, sorry for the delay, do you mean that without going into edit mode and having disabled broadcasting of all tags, the views work correctly? and the problem is still if you go to edit the device?

**Comment by unocelli** [comment] 2024-05-22 19:47
I assume the issue has been resolved in the meanwhile. I'm therefore going to close this issue.

**Closed by unocelli** 2024-05-22 19:47 UTC
