### ISSUE TITLE
Chart pop-up legend is missing values

### ISSUE THREAD

**Issue by microdeth** [frangoteam/FUXA#732] opened 2023-03-14 14:46 UTC
Hi, the chart pop-up legend shows the values only if they are integer. If any fractional part presents they are missing from the pop-up legend.
![image](https://user-images.githubusercontent.com/127868343/225038090-6d6989c8-22c0-437d-81a3-e47066e18d16.png)

**Comment by unocelli** [comment] 2023-03-14 19:08
Hi, Thanks for the report. I can reproduce it and I will fix it as soon as possible.

**Comment by microdeth** [comment] 2023-03-16 06:02
Thank you!

**Comment by unocelli** [comment] 2023-03-18 19:19
Hi,
I can't reproduce any more the issue, in any case now I have removed in chart legend the formatting of digits (the reason for the issue) being configurable in tag property.

**Comment by microdeth** [comment] 2023-03-19 12:58
Hi Umberto,
First, thanks for the great job you've done so far -- I'm looking for the
free SCADA system for my projects and yours is the most promising so far :)
Sorry, if I misbehave in any manner. I'm very new to Github and probably
don't know how things are being done there. You said it's fixed, then I
checked (after update) and saw it's not -- that's why I raised a flag
again. Mb I need to wait for the next release? Please let me know.

Anyway, you're doing the cool things and I'd prefer to stay in contact if
you don't mind :)

Yours,
Dima.


вс, 19 мар. 2023 г. в 01:19, Umberto Nocelli ***@***.***>:

**Comment by unocelli** [comment] 2023-03-19 15:19
Hi, no problem.
can you check if you have the latest version?
![image](https://user-images.githubusercontent.com/48684550/226185940-80ff18ea-5717-4077-9c7f-9925f424fcfd.png)

**Comment by microdeth** [comment] 2023-03-20 06:48
Hi Umberto,
I've updated FUXA once more (now minor ver is 12) and everything is great
now!
Thank you :)
BTW, does FUXA stands for `fuchia'?

Regards,
Dima.

вс, 19 мар. 2023 г. в 21:19, Umberto Nocelli ***@***.***>:

**Comment by unocelli** [comment] 2023-03-21 19:08
Hi, **F**rangoteam UX **A**pplication

**Comment by unocelli** [comment] 2023-03-21 19:09
I am going to close this as resolved. let us know if you have any issues.

**Closed by unocelli** 2023-03-21 19:09 UTC
Labels: fixed

**Comment by microdeth** [comment] 2023-03-22 05:47
Thanks, clear.
Dina.

ср, 22 мар. 2023 г., 01:09 Umberto Nocelli ***@***.***>:
